version: '3.2'

services:
  php-cli:
    container_name: php-cli-test-performance
    build:
      context: ./docker/php
    volumes:
      - ~/.ssh:/home/www-data/.ssh
      - ./:/var/www/test-performance
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    links:
      - mysql
    ports:
      - "9009:9001"
    tty: true
    networks:
      test-performance-net:
        ipv4_address: 172.100.0.5
    environment:
      PHP_IDE_CONFIG: "serverName=test-performance"

  mysql:
    container_name: mysql-test-performance
    image: mysql:5.7
    restart: always
    ports:
      - "3336:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql-datavolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    networks:
      test-performance-net:
        ipv4_address: 172.100.0.6

  mysql-clone-1:
    container_name: mysql-clone-1-test-performance
    image: mysql:5.7
    restart: always
    ports:
      - "3337:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql-clone-1-datavolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    networks:
      test-performance-net:
        ipv4_address: 172.100.0.7

networks:
  test-performance-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/24
    driver_opts:
      com.docker.network.bridge.name: br_tp

volumes:
  mysql-datavolume:
  mysql-clone-1-datavolume: